### ISSUE TITLE
[LAG] 在YT看重播影片載入PTT會LAG

### ISSUE THREAD

**Issue by dolanmin** [zoosewu/PTTChatOnYoutube#102]
**問題描述**
在YT看重播影片載入PTT會LAG

**重現問題**
在還沒載入PTT之前都很正常
只要一讀取完聊天室
網頁就會變得很卡，按暫停都會延遲
有把硬體加速開啟或關閉都一樣
有用過EDGE跟Chrome都一樣
請問該怎麼處理

**Comment by zoosewu** [comment]
連線設定那邊有一個關閉灰色漸變提升效能打勾試試看
