### ISSUE TITLE
[BUG] 聊天室高度太高

### ISSUE THREAD

**Issue by eight04** [zoosewu/PTTChatOnYoutube#104]
**問題描述**
在筆電上（1366x768），介面的高度遠超過螢幕高度，看不到最下方的推文。

**重現問題**
1. 在 youtube.com 啟動 PTTChatOnYoutube

**預期行為**
或許可以設定和影片同高？或是設成視區高度 - Youtube 導行列高度 - 留白高度。

**套件資訊截圖**
![image](https://user-images.githubusercontent.com/1324510/154858430-ade06691-b39a-42ad-97fe-e8d29f0fd625.png)
![image](https://user-images.githubusercontent.com/1324510/154858453-c8184716-421d-478a-945a-d802b0bee94d.png)

**其他畫面截圖**
![image](https://user-images.githubusercontent.com/1324510/154858340-e2c2f4bc-83d4-4814-b2c8-378148dea769.png)

**相關訊息:**
 - 使用的作業系統: Windows 10
 - 使用的瀏覽器: Firefox Nightly 99.0a1
 - 使用的套件版本: 2.8.15
 - 使用的網站網址: https://www.youtube.com/watch?v=7vdop_hHaLE
 - 讀取的文章代碼: #1VbBD4RZ (C_Chat)
 - 發送的推文內容:

**其他內容**
N/A

**Comment by crimsonmoon9** [comment]
連線設定 - 套件設定 - 套件長度那裡可以調整喔
