### ISSUE TITLE
[BUG] 更新2.8.50後，在Youtube 上按下"P" 按鈕後 "P"按鈕消失，無法關閉PTTChat

### ISSUE THREAD

**Issue by kevin12314** [zoosewu/PTTChatOnYoutube#108]
**問題描述**
更新2.8.50板後，按下"P" 按鈕開啟畫面後，"P" 按鈕就消失，造成無法關閉，將按鈕z-index調高就可以看見

**重現問題**

1. 在Youtube直播畫面
2. 點了"P"按鈕
3. PTTChat開啟，但"P"按鈕消失

**預期行為**
"P"按鈕應該存在。

**套件資訊截圖**

**其他畫面截圖**
未開啟時
![image](https://user-images.githubusercontent.com/10508800/162356397-dffee177-b383-46c9-ae03-11ab512305c7.png)

開啟後
![image](https://user-images.githubusercontent.com/10508800/162356482-25cfbe61-a738-44b5-980e-ca803b39eb36.png)

**相關訊息:**
 - 使用的作業系統：Windows 11
 - 使用的瀏覽器: Microsoft Edge 
 - 使用的套件版本: 2.8.50
 - 使用的網站網址: Youtube
 - 讀取的文章代碼:
 - 發送的推文內容:

**其他內容**
任何其他能幫這我了解你發生問題的描述或內容。

**Comment by zoosewu** [comment]
問題已修正
