### ISSUE TITLE
[建議]搜尋標題時只搜尋特定推數以上文章

### ISSUE THREAD

**Issue by THAR4y** [zoosewu/PTTChatOnYoutube#109]
因為常搜尋的文章推數都很高，希望能夠讓搜尋文章直接侷限於特定推數以上，

雖然能透過文章代碼直連但不夠迅速。

之前好像有看過這樣的修改，希望能協助，謝謝。

**Comment by zoosewu** [comment]
之後會改成更多元的搜尋方式
包含推文數、作者、不列關鍵字
