### ISSUE TITLE
[BUG] 搜尋LOL版賽事文章 過一陣子就會抓錯篇

### ISSUE THREAD

**Issue by gcobc12632** [zoosewu/PTTChatOnYoutube#120]
**問題描述**
搜尋LOL版賽事文章的時候 一開始正常
過一陣子就會抓錯文章

**推測**
猜測是LOL版通常會把賽事文章置底 於是腳本會優先抓到置底文
等到有新文章出現後 置底文會被往下推擠 於是腳本抓到的文章位置就錯位了

**重現**
如圖所示 假設目前抓的是LPL賽事置底文
https://i.imgur.com/ziS5XI7.png

有新文章後LOL賽事文被往下擠 變成版規文
https://i.imgur.com/BxFc4xC.png

然後腳本也確實抓錯變成版規了
所以推測應該是正確的？

**解法？**
若能在更新文章之前多加一個S指令 可以無視置底文 只看單篇文
說不定就不會導致錯位了？

**其他**
LOL世界大賽也近了 之後用越來越常用這腳本
希望能趕快修正 感謝

**相關訊息:**
 - 使用的作業系統: Win10
 - 使用的瀏覽器: Firefox 104.0
 - 使用的套件版本: 3.0.6

**Comment by zoosewu** [comment]
感謝建議
S感覺是一個不錯的方法
我會再測試看看效果如何

**Comment by gcobc12632** [comment]
第2014行
this.insertText('NPP#' + this.postData.key + '\nr');

改為
this.insertText('NPP#' + this.postData.key + '\nSr');

目前在LOL版爬LCK賽事文

版主已經將該篇文置底 + 出現新文章後也沒抓錯篇

似乎沒問題？再觀察看看

**Comment by zoosewu** [comment]
更新新版了 可以重新下載試試
