### ISSUE TITLE
[BUG] 若直播開始前有預告片 則推文不會更新

### ISSUE THREAD

**Issue by gcobc12632** [zoosewu/PTTChatOnYoutube#123]
**問題描述**
有些成員會放預告片（就是直播還沒開始時的短影片
若在直播開始前開啟套件並讀取文章的話
會發現讀取完後不會自動更新推文

**重現問題**
在任何一個有預告片的直播開始前開啟套件並讀取文章
都會出現此問題

**套件資訊截圖**
https://i.imgur.com/UtFMIRN.png
由圖可知 套件在讀取完文章後 就停擺了

**相關訊息**
 - 使用的作業系統: Win10
 - 使用的瀏覽器: Firefox 104.0.2
 - 使用的套件版本: 3.0.7

**其他內容**
可能是因為預告片被視為影片
所以當開啟套件時 被誤以為是在補檔而不是直播
才導致不會自動更新推文？

**Comment by zoosewu** [comment]
能詳細解釋一下預告片是什麼意思嗎，是Youtube會有兩分鐘倒數的那種影片嗎?

**Comment by gcobc12632** [comment]
舉個例子
https://www.youtube.com/watch?v=RYSd-N4MQK4

博衣預定6點直播 目前還沒開始
但點進網頁還是會看到影片播放
youtube會顯示個「預告」
https://i.imgur.com/ndaQAXX.png

如果這時候開啟套件讀取文章的話
似乎就會被視為影片而不是直播
導致不會自動更新推文

**Comment by zoosewu** [comment]
我一開始對預告的理解一直都是Vtuber出MV時設定首播時間開播前倒數的那個東西
但是從你的描述看起來是實況開始前會出現的東西
我這樣理解應該沒錯吧

![image](https://user-images.githubusercontent.com/75579796/191247038-0f56facf-0471-49cc-ae79-18ff956a3417.png)
我直接點一個實況
套件狀態解讀為實況
所以代表除了它在預定實況時
除了顯示封面跟倒數之外還會播另外一個影片
然後這個影片類型是預告

我想問一下什麼情況會出現這個預告
是每個實況開始前都會出現嗎?
還是有些實況開始前才會出現?
因為實況觀看習慣的不同我沒有遇過這種東西
想要理解能在什麼情況下穩定的觸發這個狀況
例如博衣的實況開始前都會有預告之類的

**Comment by zoosewu** [comment]
問題應該修正了，
更新之後再試試看。
