### ISSUE TITLE
[建議] 新增virtual scroll

### ISSUE THREAD

**Issue by 52326125** [zoosewu/PTTChatOnYoutube#14]
**你的提案是因為發生某些問題嗎?**
讀取太多推文網頁效能會變差

**你期待的改進方案**
稍微看了一下code，你應該是直接把chatlist的資料用v-for印出來，這樣會造成render過多的dom而lag
可以使用virtual scroll去控制reder的chat-item數量

**Comment by zoosewu** [comment]
非常感謝 

我也因為推文太多導致效能低這個問題落困擾很久了

第一次知道virtual scroll這個概念

非常有用

**Comment by zoosewu** [comment]
目前先用vue-virtual-scroller 之後如果有很大的問題，再考慮換或是自己寫一個。
