### ISSUE TITLE
[建議] Youtube劇院模式與聊天室的位置（仿Twitch

### ISSUE THREAD

**Issue by gcobc12632** [zoosewu/PTTChatOnYoutube#16]
下圖是Youtube預設檢視模式時 聊天室與影片的位置
可以發現影片並沒有適應到滿畫面 而且聊天室上下也有空隙
[https://i.imgur.com/CcYc2oR.png](https://i.imgur.com/CcYc2oR.png)

然後下圖是開啟Youtube劇院模式時
很明顯聊天室就會被擠到下方了 看起來很不方便
[https://i.imgur.com/PrUuCoi.png](https://i.imgur.com/PrUuCoi.png)

不知道能不能像Twitch一樣
在開啟劇院模式時 影片會適應到滿畫面並且將聊天室放在右方
[https://i.imgur.com/vuIAOyl.png](https://i.imgur.com/vuIAOyl.png)

另外 我自己有在用另一個腳本 是可以將Youtube劇院模式適應到全畫面
他還會隱藏上方搜尋欄 + 將右側的捲動軸調黑 這樣就不會影響到觀看體驗
[https://i.imgur.com/QDri3BY.png](https://i.imgur.com/QDri3BY.png)
[https://greasyfork.org/zh-TW/scripts/33243](https://greasyfork.org/zh-TW/scripts/33243)

說不定可以參考看看這腳本的寫法
讓Youtube的劇院模式可以仿造Twitch的模式？

**Comment by zoosewu** [comment]
目前在Youtube跟Twitch上的UI配置都是直接使用他們的聊天室，
所以他們聊天室放在哪邊我就會直接在上面蓋一層。

如果要讓Youtube的劇院模式仿照Twitch的模式，
我可能會另外寫一個獨立的插件，
而不是在現有的插件直接改Youtube的UI配置。
不過這是一個很好的想法，
我會再想看看。

**Comment by gcobc12632** [comment]
其實預設模式就有點像Twitch的劇院模式了
只差在聊天室跟影片的部分沒有滿版 + 有礙眼的標題搜尋欄
如果用預設模式去修改說不定會比較好做？
總之我會繼續期待的

**Comment by cyfung1031** [comment]
> 其實預設模式就有點像 Twitch 的劇院模式了 只差在聊天室跟影片的部分沒有滿版 + 有礙眼的標題搜尋欄 如果用預設模式去修改說不定會比較好做？ 總之我會繼續期待的

配合 [YouTube Live Borderless](https://userstyles.world/style/7914/youtube-live-borderless) 就能解決這個問題

**Comment by gcobc12632** [comment]
> > 其實預設模式就有點像 Twitch 的劇院模式了 只差在聊天室跟影片的部分沒有滿版 + 有礙眼的標題搜尋欄 如果用預設模式去修改說不定會比較好做？ 總之我會繼續期待的
> 
> 配合 [YouTube Live Borderless](https://userstyles.world/style/7914/youtube-live-borderless) 就能解決這個問題

我後來是用這個
chrome: https://chromewebstore.google.com/detail/youtube-livestreams-theat/cmjhejfkhdonjimgkinjdombabgfbcal
firefox: https://addons.mozilla.org/zh-TW/firefox/addon/youtubelivestreamstheatermode/
功能更多而且介面更好看
