### ISSUE TITLE
[建議] 自動抓取實況開始時間

### ISSUE THREAD

**Issue by a24230928** [zoosewu/PTTChatOnYoutube#17]
**你的提案是因為發生某些問題嗎?**
若是實況VOD，需要自行輸入實況開始時間，但一般使用者很難直接找到實況開始的精準時間，因此若可以抓取影片的實況開始時間會對使用者較友善。

**你期待的改進方案**
在影片頁面中，大致看了一下發現 script#scriptTag 中有儲存影片的一些相關資訊，裡面的 startDate是原實況開始時間。

或是載入影片主頁面本身的 request （GET https://www.youtube.com/watch?v={videoId}） 裡頭也會回傳，response[2].playerResponse.microformat.playerMicroformatRenderer.liveBroadcastDetails.startTimestamp

不知道是否能從這些地方下手？

**其他內容**
script#scriptTag 示意圖
![image](https://user-images.githubusercontent.com/16871628/105567707-fe598f00-5d6e-11eb-9546-362b015b0abe.png)

startTimestamp 示意圖
![image](https://user-images.githubusercontent.com/16871628/105568018-51ccdc80-5d71-11eb-9233-b4e30156cb6c.png)

**Comment by zoosewu** [comment]
之前也有想盡量撈實況開始時間但是我找不到，感謝資訊。
我會再看一下這些資訊好不好用。

**Comment by zoosewu** [comment]
已新增功能
