### ISSUE TITLE
[BUG] 推文重複顯示

### ISSUE THREAD

**Issue by nh60211as** [zoosewu/PTTChatOnYoutube#2]
**問題描述**
推文重複顯示

**重現問題**
問題就發生了

**預期行為**
推文不會重複顯示

**插件資訊截圖**
聊天室
https://i.imgur.com/NlTcAGc.png
PTT畫面
https://i.imgur.com/tEp3m58.png
Log (影片當下時間顯示2020/12/15但是實際時間為2020/12/13)
https://i.imgur.com/7BqxFgy.png

**系統訊息:**
 - 使用的作業系統: Windows 7
 - 使用的瀏覽器及瀏覽器版本: Google Chrome 87.0.4280.88
 - 使用的插件版本: 1.0.21

**其他內容**

1. 可能是對時錯誤的問題。
1.0.21和1.0.24登入後對時都看起來不正常 https://i.imgur.com/RpLkvN3.png

2. 另外在log可以看到推文數持續增加，但是沒有實際的推文增加。
建議可以暫存最近10筆推文來尋找上次結尾行數。

**Comment by zoosewu** [comment]
對時功能只有看實況紀錄的時候會用到，目的是對齊實況時間跟推聞時間，如果是實況中或開台前的影片就完全沒用了。

目前看起來問題是在如果文章不足兩頁的時候就會出錯。推文進度是根據PTT最下面顯示的行數，例如第一頁就是01~22，那第二頁就是23~44。
計算的方法是先把第一頁找過的存起來 startline=1 endline=22，翻到第二頁的時候會拿新的startline=22 endline=44，我們就會知道targetline = oldendline - newstartline + 1=22-22+1=1 要從現在螢幕上的第一行開始找。

但是這邊再不足兩頁的時候就計算會發生錯誤，我思考一下邏輯哪邊有錯

**Comment by zoosewu** [comment]
找到問題了
PTT一次能顯示24行，扣除尾行做為系統資訊外文章能顯示23行。
但是第一頁只有顯示22行，因為發文時間下面那個橫槓不是一行。就是這個導致過短的文章會出問題，所以文章開頭行數如果小於五的話搜尋的推文就要加一。

至於近10筆推文作為搜尋條件日後可以加入作為多重判定，但是因為這是比較不穩定的資訊，所以傾向非必要不使用。

1.0.25版已修正
