### ISSUE TITLE
[建議] 輸入關鍵字找串

### ISSUE THREAD

**Issue by zoosewu** [zoosewu/PTTChatOnYoutube#20]
**你的提案是因為發生某些問題嗎?**
每次找串都要打開PTT搜尋代碼 太麻煩了

**你期待的改進方案**
用關鍵字找討論串，直接進入搜尋到的最後一個結果。

**範例layout**
https://i.imgur.com/RqedlSZ.png

**Comment by zoosewu** [comment]
這部分可能不會太快實作，會想要先把 #21 這邊弄好。

但是這個功能本身很實用，尤其是在每天都有例行串的Vtuber。

**Comment by zoosewu** [comment]
我覺得舊的AID功能抓文章的功能應該會繼續保留，然後標題搜尋功能應該以```(C_ChAT)日間直播單```這種方式去搜尋看板跟標題，節省UI的空間。

**Comment by zoosewu** [comment]
然後搜尋結果如果用下拉式選單也可以節省UI空間 例如下面這些選項
```
[03:51:25]搜尋結果
[vtub] 日間直播單 (20210330)
[vtub] 夜間直播單 (20210329)
```
預設第一個選項提示搜尋時間，讓使用者使用搜尋功能的時候有足夠的回饋。
下面就是搜尋的前20個結果(以PTT一頁為限)

不過不清楚這種UI沒有實做出來不太清楚實際上使用會不會足夠直觀及方便。

**Comment by zoosewu** [comment]
> 4. https://i.imgur.com/iZ4GpjP.gif
>    https://i.imgur.com/iY0Dutx.gif

這個我沒有看到讀完標題之後發生什麼變化，不清楚是獲得AID了還是讀完推文了。
然後這個UI有幾個問題
1.太多層了，操作變得很複雜。
2.UI變動太多，盡量避免會造成UI跳動的狀態。
2.文章標題預覽用錯UI，不應該使用輸入欄來顯示結果。
然後在UX方面我覺得有一些問題
1.不清楚讀完標題之後接下來要幹什麼，我是讀取AID了?還是連推文都讀完了?
2.不清楚套件是怎麼找串的，因為holo的關鍵字是"間直播單"，使用者如果找錯串會不知道問題在哪，該怎麼辦。
2.讀取按鈕跟確認按鈕的差別是什麼使用者會搞不清楚。

如果我對你的UIUX考量有哪邊注意的話再請跟我說。
> 5. 目前是預留「其他」供使用者自行輸入，相關操作可以參考上面的gif

我想要問的是使用者能不能幫列表新增或移除項目。
我的想法是這個套件如果放到五年後，或是在五年前就有的話，他也不會長得很奇怪。
所以我覺得直接列上去已經有的串意義不大，讓使用者能夠新增/移除列表選項的話，通用性比較高。
大概像下面這樣
https://i.imgur.com/ktP9pBL.png
UI參考: https://jsfiddle.net/Zoosewu/pta24fr9/14/
這上面是複製起來隨便改的 一些排版沒有整齊的地方就暫時忽略吧。
> 6. 因為我想說現在/以後可能會有使用者有多串的需求，加上如果看板一多，dropdown會變得很長，使用起來會造成不便，就先設計成multilevel的樣子了。倒是我反而想把這改成default的dropdown element，額外用判斷式隱藏多層或確認按鈕，可以保留擴充性。

對於現在的多串需求，其實就算把PTT上面所有固定標題的串都追起來應該也不超過十串。
所以太多串的考量我覺得應該是沒有這個必要，不過做成可以擴充的選單這個想法本身是不錯的。

多層選單的部分不知道可不可以直接做嵌套就好，像是下面這樣。
https://jsfiddle.net/Zoosewu/tjhxL9e8/11/
這是直接用原生bootstrap code，如果要把我寫的選單要弄成可以嵌套應該還要稍微改一下。
這樣的話就能避免需要考量太多層的問題。
只要在最外面設定好資料維度就可以無限加進去。

**Comment by crimsonmoon9** [comment]
> 
> 這個我沒有看到讀完標題之後發生什麼變化，不清楚是獲得AID了還是讀完推文了。

只有獲得該文章的標題、停留在該文章畫面而已。
> 然後這個UI有幾個問題
> 1.太多層了，操作變得很複雜。

實作上dropdown是可以用hover的方式開啟submenu的實際上只有點開dropdown的那次click。
> 2.UI變動太多，盡量避免會造成UI跳動的狀態。

是考量到重新render的效能影響嗎？還是想顧慮到使用者操作上的連貫性？
> 2.文章標題預覽用錯UI，不應該使用輸入欄來顯示結果。

這原本是要因應標題太長被截斷而使用marquee、方便瀏覽完整標題，但html 5似乎移除對該屬性的支援，用scss達不到想要的效果就先留著，請問有建議的顯示方式嗎？
> 然後在UX方面我覺得有一些問題
> 1.不清楚讀完標題之後接下來要幹什麼，我是讀取AID了?還是連推文都讀完了?
> 2.不清楚套件是怎麼找串的，因為holo的關鍵字是"間直播單"，使用者如果找錯串會不知道問題在哪，該怎麼辦。

雖然說這個extension是面向PTT使用者的，關於搜尋方式應該了解跟平常使用上一樣，但關於這點我正在實驗加入regular expression，希望在搜尋上能有較好的效率跟使用體驗。找錯串的話是有設計跟AID一樣的錯誤popup，但目前跟https://github.com/zoosewu/PTTChatOnYoutube/pull/38#issuecomment-816167733 是一樣的問題。
> 2.讀取按鈕跟確認按鈕的差別是什麼使用者會搞不清楚。
> 
> 如果我對你的UIUX考量有哪邊注意的話再請跟我說。
> 

關於這點會再加強UI的敘述。只保留兩個字主要是想讓按鈕大小統一、風格精簡，但結果下來似乎是省略太多了。
> > 1. 目前是預留「其他」供使用者自行輸入，相關操作可以參考上面的gif
> 
> 我想要問的是使用者能不能幫列表新增或移除項目。
> 我的想法是這個套件如果放到五年後，或是在五年前就有的話，他也不會長得很奇怪。
> 所以我覺得直接列上去已經有的串意義不大，讓使用者能夠新增/移除列表選項的話，通用性比較高。
> 大概像下面這樣
> https://i.imgur.com/ktP9pBL.png
> UI參考: https://jsfiddle.net/Zoosewu/pta24fr9/14/
> 這上面是複製起來隨便改的 一些排版沒有整齊的地方就暫時忽略吧。
> 

這點沒問題。
> > 1. 因為我想說現在/以後可能會有使用者有多串的需求，加上如果看板一多，dropdown會變得很長，使用起來會造成不便，就先設計成multilevel的樣子了。倒是我反而想把這改成default的dropdown element，額外用判斷式隱藏多層或確認按鈕，可以保留擴充性。
> 
> 對於現在的多串需求，其實就算把PTT上面所有固定標題的串都追起來應該也不超過十串。
> 所以太多串的考量我覺得應該是沒有這個必要，不過做成可以擴充的選單這個想法本身是不錯的。
> 
> 多層選單的部分不知道可不可以直接做嵌套就好，像是下面這樣。
> https://jsfiddle.net/Zoosewu/tjhxL9e8/11/
> 這是直接用原生bootstrap code，如果要把我寫的選單要弄成可以嵌套應該還要稍微改一下。
> 這樣的話就能避免需要考量太多層的問題。
> 只要在最外面設定好資料維度就可以無限加進去。

button似乎對scss的hover無回應，若要使用這個功能應該只能用dropdown，另外之前我放入scss關於submenu的程式碼大多是繼承dropdown的，只是自訂名稱跟調整它顯示的相對位置而已，修改後應該也可支援不同維度的資料，格式可套用json。

**Comment by zoosewu** [comment]
> 是考量到重新render的效能影響嗎？還是想顧慮到使用者操作上的連貫性？
就是醜而已xD 用漸變滑上滑下得會好一點。
> 這原本是要因應標題太長被截斷而使用marquee、方便瀏覽完整標題，但html 5似乎移除對該屬性的支援，用scss達不到想要的效果就先留著，請問有建議的顯示方式嗎？
直接div+border然後顯示內容就好吧我覺得。
用輸入欄的功能是讓使用者輸入資料用的。禁止輸入通常會覺得是由其他欄位控制(區碼->城市)，或是禁止改變(ID)。
> 我正在實驗加入regular expression
這部分我感覺起來有難度，我的認知中PTT有搜尋方式的限制，還有搜尋層數的上限。你可能要詳細講一下大改怎麼實作我比較能了解。
我想到的方法就是自創一個，例如```/標題&/標題2&a帳號&!排除```這樣就是四層輸入。
> 關於這點會再加強UI的敘述。只保留兩個字主要是想讓按鈕大小統一、風格精簡，但結果下來似乎是省略太多了。
恩 這部分就是要仔細斟酌的。
我之前也是因為[重啟PTT]按鈕大小不統一然後思考許多方案，最終的想法就是現在這樣，把敘述拉出來，然後按鈕只負責確認。
或許你可以在前面類別那邊增加更精確地描述?
例如
```
透過AID讀取(輸入AID欄位)[確定]
標題搜尋文章(dropdown)[搜尋]
讀取文章(顯示結果)[確定]
```
> button似乎對scss的hover無回應，若要使用這個功能應該只能用dropdown，另外之前我放入scss關於submenu的程式碼大多是繼承dropdown的，只是自訂名稱跟調整它顯示的相對位置而已，修改後應該也可支援不同維度的資料，格式可套用json。
這個只是我的想法，我"感覺"有弄好應該可以把資料維度跟選單解偶，讓資料可以塞更多維度，下拉式選單也可以不用管要做幾層，只要管自己這一層跟下一層就好。
不過這個實作起來應該也挺麻煩的，應該就先照你的想法弄成支援1或2維資料的程度就好了。

**Comment by crimsonmoon9** [comment]
照建議稍微修改了一下搜尋的UI

https://i.imgur.com/V2b6Y2e.mp4
https://i.imgur.com/zkEawm1.mp4

目前我覺得有兩點問題

1. 點擊選單後是否要有確認鍵再跳轉以防使用者誤觸
2. 自訂輸入是否要先讓使用者看到目前的標題再決定是否要跳轉，也就是當成搜尋的功能，還是僅止於進入文章而已


另外還有 f28568bc0e89cb4c801f4ce3e323f1fd58921206 css的改動會影響到其他支援網站的排版。

**Comment by crimsonmoon9** [comment]
再次修改過後的版本

- 修改選項「其他」的文字敘述
- 新增選項後會將該選項移至選單頂部並使用該選項進行搜尋，同時隱藏輸入框

https://i.imgur.com/EVpOWX7.mp4

**Comment by zoosewu** [comment]
> 1. 點擊選單後是否要有確認鍵再跳轉以防使用者誤觸
> 2. 自訂輸入是否要先讓使用者看到目前的標題再決定是否要跳轉，也就是當成搜尋的功能，還是僅止於進入文章而已

目前搜尋標題的功能我用起來蠻順暢的。

標題搜尋功能已經新增，
這個issue先關閉，
如果有其他UX改進再另外提出。
