### ISSUE TITLE
[建議] 增加暫停功能

### ISSUE THREAD

**Issue by gn01102368** [zoosewu/PTTChatOnYoutube#24]
可以增加暫停之類的功能嗎，有時候想找特定推文很快就洗掉了

**Comment by zoosewu** [comment]
目前刷新推文有兩個功能同時運作
1.自動載入新推文
2.自動滾動到目標推文

你只要用滑鼠滾輪滾動的話2的功能應該會暫停

你就可以去找特定推文吧

還是說你在什麼情況下會遇到困擾?

**Comment by gn01102368** [comment]
看來是滑鼠的問題 換另一個就沒問題了 感謝回覆

**Comment by zoosewu** [comment]
看起來目前已有的功能不會造成使用上的困擾，也沒有新增暫停功能的必要性。

如果結論有問題的話再打開這個項目。
