### ISSUE TITLE
[BUG] 點擊左上角P鍵PTT聊天室不會收起

### ISSUE THREAD

**Issue by nh60211as** [zoosewu/PTTChatOnYoutube#3]
**問題描述**
點擊左上角P鍵PTT聊天室不會收起。

**重現問題**
問題就發生了。

**預期行為**
聊天室會收起。

**插件資訊截圖**
https://i.imgur.com/vSJMNea.png

**其他畫面截圖**
(無)

**系統訊息:**
 - 使用的作業系統:Windows 7
 - 使用的瀏覽器:Chrome 87.0.4280.88
 - 使用的插件版本:1.0.26、1.0.41、2.0.2314

**其他內容**

1. 之前使用從1.0.26到1.0.41都不會遇到這個問題。會不會不是腳本本身的bug？
2. 多按幾次可以看到底下的YouTube聊天室閃現但是還是關不起來

**Comment by zoosewu** [comment]
實測了一下有可能是效能不好導致整個插件卡住 
我更新一版無特效的試試看能不能改善

**Comment by zoosewu** [comment]
暫時還不確定發生的原因
現在改善了套件的效能嘗試看看
如果不是效能問題導致的可能需要更多的資訊才能確定發生問題的原因

**Comment by nh60211as** [comment]
抱歉，找到能夠重製問題的方法了。

先說明我是用 Violentmonkey 管理腳本。
在完全乾淨只有透過 Violentmonkey 安裝此腳本的情況下不會發生這個 issue 回報的問題。

但是如果同時啟用兩個腳本的話就會發生問題，例如：

1. Violentmonkey 同時啟用兩個任意版本的此腳本。
2. Violentmonkey 啟用此腳本、Tampermonkey 也啟用此腳本

看來是我腦殘沒事去裝 Tampermonkey 的腳本，而且還裝了兩個？？？
