### ISSUE TITLE
[BUG] 文章讀取停止

### ISSUE THREAD

**Issue by Zorachristine** [zoosewu/PTTChatOnYoutube#31]
**問題描述**
文章讀取不時地會停止，偶爾是因為PTT抽風導致，但大多數是自行停止，
切換到PTT畫面後才發現是跑到別的地方。

**重現問題**
停止狀況無法預期，隨機出現，當下是F5後重新登入。

**預期行為**
希望能提供其他重啟程式的方式，因為DD總是一次追好幾個VT，整個頁面重啟就必須再次調整音量。

**套件資訊截圖**
![image](https://user-images.githubusercontent.com/73385275/108734266-420c0800-756a-11eb-8a05-205159d3bc87.png)
![image](https://user-images.githubusercontent.com/73385275/108734309-4fc18d80-756a-11eb-9e05-b39fd3bd3f07.png)

**相關訊息:**
 - 使用的作業系統:Win10 20H2
 - 使用的瀏覽器:Chrome 版本 88.0.4324.182
 - 使用的套件版本:2.3.52(或前一版本)
 - 使用的網站網址:https://hololive.jetri.co/#/watch
 - 讀取的文章代碼:#1WCu2Xw2 (C_Chat)
 - 發送的推文內容:

**其他內容**
任何其他能幫這我了解你發生問題的描述或內容。

**Comment by zoosewu** [comment]
對，有時候套件腦子進水就會跑到奇怪的地方，可是我也不知道實際發生的原因在哪。
我有一直在尋找問題發生的原因，不過通常好幾個小時才會發生一次，所以問題點很難找。
提供一個重開PTT的按鈕的確是一個簡單且有效的暫時解決方案，我有空會加上去的。

**Comment by zoosewu** [comment]
此功能已新增
