### ISSUE TITLE
[建議]希望新增支援Holodex

### ISSUE THREAD

**Issue by willie9815** [zoosewu/PTTChatOnYoutube#39]
[holodex](https://holodex.net/)是從holotools延伸的分支，功能與介面比tools更成熟，考量到未來需求([參考這篇](https://hololive.jetri.co/#/holodex))，希望ptt推文功能可以支援

**Comment by zoosewu** [comment]
我原本以為這只是單純的看剪輯網站，所以我想說支援的必要性沒有這麼大。
如果相同會有實況功能的話，應該可以試試看能不能支援。

**Comment by willie9815** [comment]
感謝大大，辛苦了。

**Comment by zoosewu** [comment]
目前最新版本已經支援holodex。 有bug的話再另開issue回報。
