### ISSUE TITLE
[BUG] Holotools開啟方式的改版有問題。

### ISSUE THREAD

**Issue by zoosewu** [zoosewu/PTTChatOnYoutube#44]
**問題描述**
Holotools裡原本的P按鈕不見了，使用者會感覺套件壞了。
建議改成P原本的P按鈕還在，或是整個打開套件。
而且P用原本的P按鈕縮小套件之後再按新按鈕會壞掉。

然後[Holotools新版](https://hololive.jetri.co/#/ameliawatchon)的P按鈕位置有問題。

**重現問題**
1.打開網站的
2.P按鈕不見了
3.感到恐慌

**預期行為**
Holotools裡的套件預設狀態設定為已開啟。
或是紀錄上一次的啟用狀態，但是初次使用建議全開。

**其他畫面截圖**
舊按鈕縮小再按新按鈕後的奇怪狀態
![image](https://i.imgur.com/YjqR8CX.png)
HT新版的P按鈕疊再一起
![image](https://i.imgur.com/fN6JGDM.png)

**相關訊息:**
 - 使用的網站網址: 
[https://hololive.jetri.co/#/watch](https://hololive.jetri.co/#/watch)  
[https://hololive.jetri.co/#/ameliawatchon](https://hololive.jetri.co/#/ameliawatchon)

**Comment by crimsonmoon9** [comment]
> **問題描述**
> Holotools裡原本的P按鈕不見了，使用者會感覺套件壞了。
> 建議改成P原本的P按鈕還在，或是整個打開套件。
> 而且P用原本的P按鈕縮小套件之後再按新按鈕會壞掉。
> 
> 然後[Holotools新版](https://hololive.jetri.co/#/ameliawatchon)的P按鈕位置有問題。

完全不知道有新版orz，修復中。
> 
> **預期行為**
> Holotools裡的套件預設狀態設定為已開啟。
> 或是紀錄上一次的啟用狀態，但是初次使用建議全開。

目前打算先照舊維持原始的樣子，只在控制列加上按鈕。
> 
> **其他畫面截圖**
> 舊按鈕縮小再按新按鈕後的奇怪狀態
> ![image](https://camo.githubusercontent.com/be28dba13f15e6889231c325c6bec6670f3f9657238221e039a33d52c841ec51/68747470733a2f2f692e696d6775722e636f6d2f596a71523843582e706e67)
> HT新版的P按鈕疊再一起
> ![image](https://camo.githubusercontent.com/bda4c127f6d0d7eef43b8a0c4702a43974fe0e24c6c2cb1edec7f9505d19ac88/68747470733a2f2f692e696d6775722e636f6d2f664e364a47444d2e706e67)
> 

以上修復進行中。
> **相關訊息:**
> 
> * 使用的網站網址:
>   https://hololive.jetri.co/#/watch
>   https://hololive.jetri.co/#/ameliawatchon

目前遇到一個問題，新版holotools在第一次切換顯示布局的時候偶爾會觸發重新整理，用不同瀏覽器測試過都一樣，找不太到它運行的邏輯。

**Comment by crimsonmoon9** [comment]
> **預期行為**
> Holotools裡的套件預設狀態設定為已開啟。
> 或是紀錄上一次的啟用狀態，但是初次使用建議全開。

#46 修改成跟以前一樣的顯示方式。
我想會用這個擴充功能的人大多會開啟聊天室，關閉只是暫時的需求，紀錄上次操作感覺不是很必要。

**Comment by zoosewu** [comment]
問題已經修復 
也增加新的方式讓使用者在不需要的時候可以把空間讓出來
