### ISSUE TITLE
[建議] 新增彈出式changelog

### ISSUE THREAD

**Issue by crimsonmoon9** [zoosewu/PTTChatOnYoutube#45]
**你的提案是因為發生某些問題嗎?**
現在的更新說明只在近期改版或看板上的更新文內，沒有點進去看的話很容易沒注意到或不知道怎麼用、改了什麼。

**你期待的改進方案**
版本更新時跳出changelog供使用者參考有什麼地方更新。

**其他內容**
其他任何內容，包含你示意圖，layout，流程圖。
無。

**Comment by crimsonmoon9** [comment]
更新說明一下：
想追加這個功能是因應 #43 在實作新版本時要兼顧舊版本的相容性，會讓程式碼比較雜亂、難以維護，
若是在版本更新時有提示新版的改動、使用方法等，或許可以直接砍除舊版的部分？
目前的想法是：
1. 儲存當前版本號。
2. 在載入時判斷更新。
3. 是否跳出更新日誌。

**Comment by zoosewu** [comment]
應該直接把近期改版功能改成彈出式視窗就好。
改成多一個div蓋在連線設定頁面的前方，然後給一個X關閉視窗就好。
然後可以直接用版本資訊去抓，如果minor改版就跳提示顯示改版資訊。

**Comment by crimsonmoon9** [comment]
> 應該直接把近期改版功能改成彈出式視窗就好。
> 改成多一個div蓋在連線設定頁面的前方，然後給一個X關閉視窗就好。
> 然後可以直接用版本資訊去抓，如果minor改版就跳提示顯示改版資訊。

我想如果是蓋放在連線頁面的話改動開啟方式還是可能會讓使用者在改版後找不到開啟方法吧，我是打算直接插在主頁面的部份，可能後續的小更新再插在連線設定頁面裡面？

**Comment by zoosewu** [comment]
插在主頁面的意思是使用者一開套件支援的網頁就會直接跳一個視窗顯示改版資訊嗎?

**Comment by crimsonmoon9** [comment]
> 插在主頁面的意思是使用者一開套件支援的網頁就會直接跳一個視窗顯示改版資訊嗎?

bootstrap有modal這個module能用，不過要插在body比較不會發生問題。
若有更新就會跳出改版資訊，反之就是正常使用。

大概像是這樣：

![3u7fn-hrkdu](https://user-images.githubusercontent.com/70936803/117536034-7badc480-b02b-11eb-818c-a91a0b0e474d.gif)

**Comment by zoosewu** [comment]
其他套件支援的網站能支援相同或類似的功能嗎?
還是現在只有在holotools上面才會有更新資訊?

**Comment by zoosewu** [comment]
目前用起來感覺有兩個問題
1.應該不需要每一板都顯示一次log，應該更一次次版號秀一次日誌就好，
不然有時候只是hotfix也會跳一次，應該會造成使用者的困擾。

2.目前的更新寫法有點難以靈活更動，
有時候會不清楚那些功能是更許久的哪些是新的。
我覺得前面可以再加一層板號陣列```msg['v_' + major + "_" + minor]```
然後新增功能就可以用```msg.v_2_6.HoloDex.push('新增按鈕在右上方控制列中，可以關閉聊天室讓出空間(限舊版)。')```的方式。
然後版本更新資訊也可以直接顯示未顯示過的，例如2.5->2.8就可以顯示2.6+2.7+2.8的更新資訊。

你覺得怎麼樣

**Comment by crimsonmoon9** [comment]
> 目前用起來感覺有兩個問題
> 1.應該不需要每一板都顯示一次log，應該更一次次版號秀一次日誌就好，
> 不然有時候只是hotfix也會跳一次，應該會造成使用者的困擾。
> 

如果在logsetting那放一個全域變數當開關，發佈新版時才打開，平時開發或或沒更新時就不會顯示出來這樣如何？
> 2.目前的更新寫法有點難以靈活更動，
> 有時候會不清楚那些功能是更許久的哪些是新的。
> 我覺得前面可以再加一層板號陣列`msg['v_' + major + "_" + minor]`
> 然後新增功能就可以用`msg.v_2_6.HoloDex.push('新增按鈕在右上方控制列中，可以關閉聊天室讓出空間(限舊版)。')`的方式。
> 然後版本更新資訊也可以直接顯示未顯示過的，例如2.5->2.8就可以顯示2.6+2.7+2.8的更新資訊。
> 
> 你覺得怎麼樣

應該是可行的，不過目前的設定應該時每天會更新吧？應該也不會有跳太多版號的問題。

**Comment by zoosewu** [comment]
功能已新增，有其他問題另開issue
