### ISSUE TITLE
[BUG] 標題搜尋輸入、預覽框不會照預期的摺疊。

### ISSUE THREAD

**Issue by crimsonmoon9** [zoosewu/PTTChatOnYoutube#48]
**問題描述**
#47 後form-row行為怪怪的，刪除後可正常摺疊。

**重現問題**
載入後的連線設定頁面。

**預期行為**
待登入點擊下拉選單後才會出現預覽框等。

**其他畫面截圖**

![image](https://user-images.githubusercontent.com/70936803/117132468-76efd300-add5-11eb-8ba5-291c80951970.png)

**Comment by zoosewu** [comment]
直接用row的話UI會有沒對齊的問題我才改成form-row，
我再另外試試看怎麼統一UI又不會影響功能好了。

**Comment by zoosewu** [comment]
功能已解決
