### ISSUE TITLE
[BUG]沒有標題的文章無法讀取

### ISSUE THREAD

**Issue by zoosewu** [zoosewu/PTTChatOnYoutube#5]
**問題描述**
許多比賽文章會把頭三行文章資訊砍掉換ANSI，導致文章讀不出來

**重現問題**
1. 登入PTT
2. 讀取文章#1V_1Gret (LoL)
3. PTT瘋狂跳針
4. 壞了 50收

**預期行為**
用其他方法讀取文章資訊取代頭三行，就不會壞掉

**插件資訊截圖**
無

**其他畫面截圖**
無

**系統訊息:**
 - 使用的作業系統[例: Win10]
 - 使用的瀏覽器:[例: Chrome]
 - 使用的插件版本:[例: 1.0.4]

**其他內容**
相關討論 https://www.ptt.cc/bbs/Marginalman/M.1610359271.A.5C2.html

**Comment by yam276** [comment]
==

**Comment by zoosewu** [comment]
目前預計的解決方法是直接把文章第一頁第二行直接擷取起來當作比對用的標題
然後時間就改為找到的第一則推文，因為Live文通常很快就會有推文。

**Comment by zoosewu** [comment]
已修正
