### ISSUE TITLE
[建議]直立畫面模式

### ISSUE THREAD

**Issue by Andreaus1986** [zoosewu/PTTChatOnYoutube#53]
**你的提案是因為發生某些問題嗎?**
目前使用雙螢幕觀看,因為空間關係副螢幕直立使用

**你期待的改進方案**
1.希望使用holotools時ptt的顯示位置能設定從右側移到網頁的底部或頂部
2.對應直立使用時套件寬度的值希望可以超過850,好設定到能在直立網頁滿版顯示

**你考慮過的其他替代方案**
使用第二個網頁只開ptt, 但是希望還是能一個網頁較方便

**其他內容**
![image](https://user-images.githubusercontent.com/71087822/117518121-2e9d0480-afd1-11eb-944d-62370995e59b.png)

**Comment by zoosewu** [comment]
不太能理解放到頂部或放到底部之後套件會長什麼樣子，套件改成倒的嗎?
目前文字都使用橫書，如果介面改為倒的應該會不方便顯示及瀏覽吧。

如果有更多是意圖的話我能更好理解你想的解決方案大概長怎樣。

**Comment by crimsonmoon9** [comment]
> 不太能理解放到頂部或放到底部之後套件會長什麼樣子，套件改成倒的嗎?
> 目前文字都使用橫書，如果介面改為倒的應該會不方便顯示及瀏覽吧。
> 
> 如果有更多示意圖的話我能更好理解你想的解決方案大概長怎樣。

他指的應該是類似這種插入方式，暫時加入 #43 處理中。

![image](https://user-images.githubusercontent.com/70936803/117535858-4bb1f180-b02a-11eb-89e7-9722c75c95be.png)

**Comment by Andreaus1986** [comment]
對對, 就是上面的示意方式. 只是套件插入排列的位置改變, 改到下面,但文字方向不變

**Comment by zoosewu** [comment]
我們之後Holodex會支援讓套件可以自訂位置及大小，不過這方面的功能還在討論，看起來你只能先暫時這樣了。
然後套件你可以用 http://blank.org/ 這個空白網站

**Comment by Andreaus1986** [comment]
喔喔這個好, 感謝

**Comment by crimsonmoon9** [comment]
@Andreaus1986 這樣有符合你的預期嗎？

https://github.com/crimsonmoon9/PTTChatOnYoutube/blob/7d9263d3a3c5a991f6acdf08a5e5c1d822b25f60/PTTChatOnYt.user.js

**Comment by Andreaus1986** [comment]
Yes, 成功了
![image](https://user-images.githubusercontent.com/71087822/117735191-8e8ce880-b227-11eb-9b63-37d787c279c9.png)
