### ISSUE TITLE
[BUG] LOL版全部文章都不能用

### ISSUE THREAD

**Issue by wudishidove** [zoosewu/PTTChatOnYoutube#55]
**問題描述**
其他版的文章都能用，LOL版的全部不行，雖然套件的PTT業面能進去LOL板就是了，但是聊天室沒辦法讀

**重現問題**
請描述怎樣的操作流程能重現你的問題:

任何LOL版的文章代碼都讀不到聊天室
結果過一段時間突然讀到其他文章，看起來是其他文章的，神奇
**預期行為**
能正常更新聊天室

**套件資訊截圖**
![image](https://user-images.githubusercontent.com/39882451/117544556-a2342580-b054-11eb-872e-31323b8a8440.png)
![image](https://user-images.githubusercontent.com/39882451/117544570-aceeba80-b054-11eb-8bf0-b2c8ee40539e.png)
正常聊天室應該畫面:
![image](https://user-images.githubusercontent.com/39882451/117544580-b8da7c80-b054-11eb-97f8-43648f5799e8.png)

**相關訊息:**
 - 使用的作業系統[例: Win10]
 - 使用的瀏覽器:[例: Chrome]
 - 使用的套件版本:2.6.41
 - 使用的網站網址:https://www.twitch.tv/lolpacifictw
 - 讀取的文章代碼:#1WbJBFgK (LoL)

**Comment by zoosewu** [comment]
套件是透過搜尋右上方的看板```看板《LOL》```來判斷是不是進入正確的看板，不過現在LOL版版主群ID+版標太長導致那個東西被擠出去了，我再來想想該怎麼用其他的判斷方法。

**Comment by zoosewu** [comment]
感覺要用其他方法去獲得目前所在的看板狀況，
我想到的是用i判斷之後去撈第頭兩個板主ID然後記起來。

**Comment by crimsonmoon9** [comment]
> 感覺要用其他方法去獲得目前所在的看板狀況，
> 我想到的是用i判斷之後去撈第頭兩個板主ID然後記起來。

偵測不到看板名稱時直接進入文章找板名如何？

**Comment by zoosewu** [comment]
有些看板，
尤其是現在不能使用的LOL板許多串會直接改掉前三行的文章資訊改放ANSI，
感覺進文章找會有很多麻煩。

**Comment by gcobc12632** [comment]
進入看板後按 ctrl+w 可以看到看板的路徑 從這裡抓看板名稱如何？
示意圖：
https://i.imgur.com/wbOUWEm.png

**Comment by AlexisKerib** [comment]
去ALLPOST版開啟同篇文章可順利載入推文
例如
#1YUW5_VZ (LoL)
改
#1YUW5_VZ (ALLPOST)
