### ISSUE TITLE
[建議] markdown file更新、打release tag

### ISSUE THREAD

**Issue by crimsonmoon9** [zoosewu/PTTChatOnYoutube#74]
**你的提案是因為發生某些問題嗎?**
我看使用教學那裡還停在滿前面的階段，要不要更新一下內容，我這裡稍微弄了一些。

**其他內容**
要不要在發佈到greasyfork的那次commit上打tag，方便在github上追蹤。

**Comment by zoosewu** [comment]
> 要不要在發佈到greasyfork的那次commit上打tag，方便在github上追蹤。

不是很懂，
在greasyfork那邊打#74 也會在這邊標註的意思嗎?

**Comment by crimsonmoon9** [comment]
用github的release功能可以直接上tag，或是在local端tag後push到github上也可以。
這樣比較方便知道上次放到geasyfork的版本是哪個。

**Comment by zoosewu** [comment]
最近這一版測試之後沒問題上版本之後會一起弄一弄

**Comment by zoosewu** [comment]
已解決
