### ISSUE TITLE
[BUG] 套件嵌入Holodex cell 出現問題

### ISSUE THREAD

**Issue by zoosewu** [zoosewu/PTTChatOnYoutube#78]
**問題描述**
#73 剛剛發現如果修改布局的話
會有機率隨機跳到不知道哪邊的cell上面
而且長寬會歪掉
div的前後排序也會跑掉
感覺是嵌入的寫法寫得太複雜導致奇怪的bug發生

**重現問題**
1. 布局選擇2*2 chat
2. 把chat改成套件
3. 布局選擇side chat 1
4. 套件會跑到奇怪的地方、div前後排序可能會壞掉
5. 布局選擇2*2 chat
6. 套件會跑到奇怪的地方、div前後排序可能會壞掉

**預期行為**
如果把有套件的cell移除
應該直接讓它消失
等到重新選擇再出現

**其他畫面截圖**
莫名跑到左上角的cell裡面寄生
![image](https://user-images.githubusercontent.com/75579796/123517116-edbc9480-d6d1-11eb-88fd-7e2e796fb14c.png)
被原生聊天室的div擋住
![image](https://user-images.githubusercontent.com/75579796/123517173-16448e80-d6d2-11eb-925d-1898ccc21c2c.png)

**Comment by crimsonmoon9** [comment]
嗯...之前有出現過卻無法重現的bug，修復中
