### ISSUE TITLE
[BUG] 文章無法讀取

### ISSUE THREAD

**Issue by gn01102368** [zoosewu/PTTChatOnYoutube#79]
**問題描述**
在連線設定輸入代碼搜尋後沒有反應

**重現問題**
請描述怎樣的操作流程能重現你的問題:
1. 連線設定
2. 文章代碼後按讀取後
3. 沒有反應

**相關訊息:**
 - 使用的作業系統 WIN7
 - 使用的瀏覽器Chrome 91.0.4472.114 
 - 使用的套件版本:2.7.28
 - 使用的網站網址:hololive.jetri.co
 - 讀取的文章代碼:#1WsxicvY (Stock) 不只這個文章
 - 發送的推文內容:

**其他內容**
PTT畫面會停在文章列表

**Comment by crimsonmoon9** [comment]
應該是跟 #55 類似的問題，後面的《看板》stock被擠掉了。
可能要找別的辦法判斷目前在哪個看板。
