### ISSUE TITLE
[BUG] holodex 首頁無顯示P的按鍵

### ISSUE THREAD

**Issue by Sagemode35** [zoosewu/PTTChatOnYoutube#82]
已關閉LiveTL ytcfilter測試一樣
這個是首頁直接開啟
https://i.imgur.com/5QKlHHH.jpg
這個是多窗模式
https://i.imgur.com/jtPNdlI.jpg
holodex的P好像會被放到聊天室外的右上角
而不是ytb內的聊天室左上角
多窗下沒問題，如果首頁單選某個實況會自動被擋掉

**Comment by crimsonmoon9** [comment]
> 這個是首頁直接開啟
> https://i.imgur.com/5QKlHHH.jpg

目前只有支援多窗模式，若有需要日後會再更新支援。
不過我的畫面不太一樣，不知道是不是沒登入的關係，還是你有裝額外的extension？

![image](https://user-images.githubusercontent.com/70936803/125613631-696c27ab-bfe0-43fc-91da-0c192d56cc26.png)

> 這個是多窗模式
> https://i.imgur.com/jtPNdlI.jpg
> holodex的P好像會被放到聊天室外的右上角
> 而不是ytb內的聊天室左上角

這是這個版本的正常設定，目前已經在開發其他種插入模式。
> 多窗下沒問題，如果首頁單選某個實況會自動被擋掉

因為腳本的設定是在多窗工具 ( https://holodex.net/multiview )下才會觸發
若是直接從首頁點擊實況會進入 https://holodex.net/watch/*

當前版本(v2.7.28)若要使用PTT聊天室請先移至多窗工具頁面。

**Comment by TsungLinYeh** [comment]
最近 holodex 已改版將 PTT 插件整合進多窗模式的網格內
可以點格子左下角編輯將聊天室的格子替換為 PTT 或是加一個新的格子放
