### ISSUE TITLE
[BUG]最近EDGE會進不去留言區

### ISSUE THREAD

**Issue by radseg** [zoosewu/PTTChatOnYoutube#84]
**問題描述**
https://i.imgur.com/tqaQTGq.gif
https://i.imgur.com/67K20nr.gif

**重現問題**
請描述怎樣的操作流程能重現你的問題:

單純用EDGE登入PTT，按直播單然後留言顯示不出來
用讀取的也沒反應，最近才會這樣

剛測試chrome和firefox是正常的

**相關訊息:**
 - 使用的作業系統 : win10
 - 使用的瀏覽器 : EDGE 版本 92.0.902.78 (官方組建) (64 位元)
 - 使用的套件版本 : 2.7.28
 - 使用的網站網址 : https://holodex.net/multi
 - 讀取的文章代碼 : Hololive直播單

**Comment by zoosewu** [comment]
目前我測試都沒有問題
你是一直都沒辦法使用嗎?
還是有時候OK有時候不行?
你能不能幫我試試看chrome有沒有正常運作

**Comment by radseg** [comment]
最近轉chrome來替代EDGE，所以整個忘了回來看
chrome和firefox都是正常的
但是唯獨只有EDGE不行，狀況還是一樣
是每次都不行，完全沒辦法用的狀態
按留言串程式會切過去，但完全沒有留言，整個是空的
EDGE現在版本是 93.0.961.38 (官方組建) (64 位元)

(如果作者無法重現的話可能也沒辦法修，我轉Chrome也沒啥差就是了)

**Comment by zoosewu** [comment]
目前我用edge都一直能正常使用
有其他人也有edge不能用的情況
我會再找找為什麼會有些人的edge會發生無法使用的情況
