### ISSUE TITLE
[BUG] 安裝BetterTTV後Twitch無法顯示

### ISSUE THREAD

**Issue by gcobc12632** [zoosewu/PTTChatOnYoutube#85]
**問題描述**
此腳本似乎與BetterTTV衝突？
安裝後就後無法顯示聊天室了

**重現問題**
啟用BetterTTV就無法顯示聊天室
但停用之後就正常了

**其他畫面截圖**
https://i.imgur.com/7nBMEfD.png

**相關訊息:**
Win10x64 21H2
Firefox91.0.2
2.7.28
https://www.twitch.tv

**其他內容**
BetterTTV是一個Twitch的擴充套件
可以大量的自訂Twitch的樣式以及支援更多表情符號
使用者眾多
希望這兩者能並存

**Comment by crimsonmoon9** [comment]
應該是發佈前忘記重新編譯scss了，修正之後應該就能正常使用了。

https://github.com/zoosewu/PTTChatOnYoutube/blob/61743698da310e159cba16c921e92972cfa5a26c/scss/index.scss#L46-L50
\
https://greasyfork.org/zh-TW/scripts/418469-pttchatonyoutube/code _(Line3636)_
```
#PTTChat {
  all: revert; }

**Comment by gcobc12632** [comment]
有了 正常了 期待你們把新版放上去
只能先暫時用自己編輯的了
