### ISSUE TITLE
[建議] 字串黑名單

### ISSUE THREAD

**Issue by ha02** [zoosewu/PTTChatOnYoutube#89]
**你的提案是因為發生某些問題嗎?**
目前已經有帳號型黑名單，但有時候只是對於某些東西或某些實況主不敢興趣，例如我完全沒在看apex，不想看到任何相關的字句出現在聊天室

**你期待的改進方案**
我目前自行加了這段在原本的if (!isMatch) 上方，看有沒有更好的寫法或做成UI方便編輯

if (!isMatch) {
    var black_arr = ["apex","吃雞","中風","xxx自行添加"];
    for (let value of black_arr){
        var reg = eval ('/' + value + '/i');
        if (reg.test(msg)){
            isMatch = true;
            break;
        }
    }
}

**Comment by zoosewu** [comment]
是針對關鍵字的遮擋嗎?

**Comment by ha02** [comment]
是，雖然現在很多人都是DD，但也不太可能D到所有的男女團
尤其當自己在追的實況主跟沒在追的實況主歌回同時間開的時候，就會覺得XXX相關的推文好煩啊XD
這時候就可以把XXX加進關鍵字，濾掉有提到XXX的推文
