### ISSUE TITLE
[BUG] 無法正常讀取文章並顯示聊天

### ISSUE THREAD

**Issue by a24230928** [zoosewu/PTTChatOnYoutube#9]
**問題描述**
登入後，輸入數個不同文章AID（不同版、不同文章皆有此問題），會持續跳出「文章AID錯誤，文章已消失或是你找錯看板了。」，嘗試使用教學文章中的範例直接複製貼上也會出現。

**重現問題**
1. 登入（有看到登入成功訊息）
2. 貼上文章AID並點選讀取
3. 即會不斷跳出上述訊息

**預期行為**
應能正常讀取推文

**插件資訊截圖**
![image](https://user-images.githubusercontent.com/16871628/104317497-00bf1c00-5519-11eb-825e-094bdcb29e49.png)
![image](https://user-images.githubusercontent.com/16871628/104317514-0583d000-5519-11eb-9ac6-cda3d1667423.png)
![image](https://user-images.githubusercontent.com/16871628/104317531-09afed80-5519-11eb-8614-d0a127b7ab57.png)
![image](https://user-images.githubusercontent.com/16871628/104317551-0fa5ce80-5519-11eb-9e44-be6ec5f98e44.png)

**系統訊息:**
 - 使用的作業系統: Windows 10 2004
 - 使用的瀏覽器: Chrome 87.0.4280.14
 - 使用的插件版本: 2.0.2380

**其他內容**
在 「PTT 畫面」中，能看到不斷在文章與文章列表中切換（可見截圖），文章也確實與輸入的AID吻合，但不確定為何無法正常讀取。

**Comment by zoosewu** [comment]
可以貼上你使用的文章AID嗎

**Comment by a24230928** [comment]
對的，我剛剛嘗試上面的那個AID也是一樣的
目前是沒有一篇能成功的，這邊是幾個目前試過，有此問題的：
#1V_NCa-w (C_Chat)
#1V_QXD7I (C_Chat)
#1V_QUn7z (Gossiping)

**Comment by a24230928** [comment]
> 每一篇文都會有同樣的問題?
> 我記得有些範例的文章好像是我亂打的會找不到文章
> 試試這篇看看 #1V_NCa-w (C_Chat)
> 
> 目前新版的Log還沒串好資料，
> 所以找Bug比較不方便
> 如果你想用的話可以先試試看舊版
> https://raw.githubusercontent.com/zoosewu/PTTChatOnYoutube/ver1/Main.user.js

![image](https://user-images.githubusercontent.com/16871628/104324727-c35f8c00-5522-11eb-9b50-7bd8ac21ade6.png)
舊版一樣會在文章與列表間迅速切換，並顯示AID錯誤的訊息，這邊提供log的畫面

**Comment by zoosewu** [comment]
你本身有用瀏覽器上PTT嗎 term.ptt.cc
如果有的話你有用其他PTT插件嗎

**Comment by a24230928** [comment]
我是裝 PttChrome 並透過
https://iamchucky.github.io/PttChrome/index.html?ssh=true
這樣是一樣的嗎？

**Comment by zoosewu** [comment]
原作者有開發直接用瀏覽器可以看的方法 
直接連 https://term.ptt.cc/
我不清楚這會不會造成影響
PttChrome 有提供什麼特別的功能嗎?
如果沒有的話你你可以移除掉改用網址直連的

**Comment by a24230928** [comment]
因為我用直連的方法會無法使用推文自動更新，所以才改回安裝插件的

**Comment by zoosewu** [comment]
喔喔
那我裝PttChrome試試看問題在哪

**Comment by a24230928** [comment]
好的，感謝～

**Comment by zoosewu** [comment]
我裝了PttChrome之後使用了一下再用插件，插件依然很正常的在運作。可能我使用的方法沒有達到特定的條件。
然後也有其他使用者回報我有遇到一樣的狀況，他的情況是曾經用過PttChrome，不過現在使用term.ptt.cc。
所以我想在蒐集更多情報，希望遇到問題的人能在這個issue提供以下訊息:
1.使用或曾經使用PttChrome時開啟的非官方功能，以及如何開啟(自動載入推文之類的)
2.使用或曾經使用term.ptt.cc時安裝的其他套件(用暴力猴裝的)，以及有沒有依照下面網址排除
https://github.com/zoosewu/PTTChatOnYoutube/tree/master/homepage#%E5%85%B6%E4%BB%96%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A0%85
3.依照下面圖片指示打開回報模式，然後使用套件到發生問題的地方後按F12把資訊截圖給我，謝謝。
https://imgur.com/O9xGUY2

如果沒有Github帳號的話可以使用站內信。

**Comment by zoosewu** [comment]
這邊修改了文章的判定，不確定有沒有解決問題，如果有這個問題的人請這個[連結安裝](https://raw.githubusercontent.com/zoosewu/PTTChatOnYoutube/mainDev/PTTChatOnYt.user.js)來試試看。

如果還是有問題的話希望能依照[這個](https://github.com/zoosewu/PTTChatOnYoutube/issues/9#issuecomment-759274422)把Console畫面截圖給我。
如果可以成功讀取文章了請回報一下讓我知道問題解決了。

**Comment by zoosewu** [comment]
找到問題了 因為term.ptt.cc裡面設定了好讀模式
所以進入文章之後格式跑掉而無法正常讀取資訊
暫時的解決方法就是關閉好讀模式
(打開網頁版->右鍵->setting->"Enable easy reading article view. (experimental)"取消打勾)

**Comment by a24230928** [comment]
解決了，感謝( •̀ ω •́ )✧
