### ISSUE TITLE
[BUG]ICON消失

### ISSUE THREAD

**Issue by BBSecondR** [zoosewu/PTTChatOnYoutube#93]
**問題描述**
PTT的Icon消失

**重現問題**
重整網頁之後就消失了

**預期行為**
應能正常顯示

**套件資訊截圖**
https://i.imgur.com/anzTAUv.png

**其他畫面截圖**

**相關訊息:**
 - 使用的作業系統:W10
 - 使用的瀏覽器:firefox 90.1
 - 使用的套件版本: v2.8.41
 - 使用的網站網址:holotools , holodex , Youtube

**Comment by zoosewu** [comment]
原本正常使用，重新整理之後消失了的意思嗎?
重開瀏覽器後依然是消失的狀態嗎?

**Comment by BBSecondR** [comment]
重整,重開瀏覽器,重新安裝插件,重開機都試過依然消失

**Comment by WWR1234** [comment]
chrome也遇到同樣狀況 跟BBS大一樣方法都試過 原本能用的網站都跑不出來

**Comment by TWxocolatl** [comment]
更新後發生一樣的狀況，後來發現是插件內容程式碼全消失了剩備註，重新去把PTTChatOnYt.user.js的內容複製貼上回去才恢復

**Comment by stu43005** [comment]
https://greasyfork.org/zh-TW/scripts/418469-pttchatonyt

腳本似乎已被刪除

**Comment by WWR1234** [comment]
應該是2.8.8.1的更新有問題 我用2.8.4的更新檔就能用 按下檢查更新到2.8.8.1就被清空了

**Comment by Catossun** [comment]
我在版本 2.8.4.1 也有同樣地狀況，按下更新到 2.8.8 就出現了，應該是版本號最後是 ".1" 的版本有問題。
有遇到類似問題的人，可以到[腳本網站](https://greasyfork.org/zh-TW/scripts/418469-pttchatonyt)裡面的歷史選擇其他版本降版使用。

**Comment by zoosewu** [comment]
![image](https://user-images.githubusercontent.com/75579796/133072651-a1bb458c-5a38-44ed-90f3-d8d95e7f99b5.png)
![image](https://user-images.githubusercontent.com/75579796/133072695-19347aba-4007-443b-8413-51e80b420675.png)
我上傳的版本沒有發現有四個版號的狀況
你們可以檢查一下有問題的版本版號是多少嗎
然後有問題的人[點我](https://greasyfork.org/zh-TW/scripts/418469-pttchatonyoutube/versions?version=968241)可以選擇舊版安裝
目前確認沒問題的應該是v2.7.28版

**Comment by BBSecondR** [comment]
2.8.8可正常運作
發生問題的是v2.8.41

**Comment by zhongyuanli-houzz** [comment]
v2.8.4.1 看起來code是空的
![image](https://user-images.githubusercontent.com/84754984/133081003-188657a3-b3ad-461e-a94c-9fa6ad12834c.png)

**Comment by zhongyuanli-houzz** [comment]
重新安裝v2.8.8就可以了

**Comment by zoosewu** [comment]
喔 我看到截圖知道問題在哪邊了。

昨天我的套件被檢舉內容含有極簡化代碼，違反他們的守則，然後套件就被砍了。
所以昨天有一段時間套件的頁面消失了。
目前我已經更新了套件並申訴之後已經解鎖。

如果遇到bug的人可以安裝2.8.8版應該就能恢復。
Edge的部分使用者安裝之後還是呈現壞掉，
這時候需要連暴力猴都重新安裝才能使用。

如果還是無法解決問題或有其他問題的話再下面回報。
